<a href="https://colab.research.google.com/github/iamnaofil/NumPyPracticeAll_in_One/blob/main/Numpy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import numpy as np


**creation of Empty array**

In [49]:
np.array([])

array([], dtype=float64)

**Array of Numerics**

In [116]:
np.array([*range(1,10)]) #This is some trick to print list of numbers

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**Alphabets Array**

In [122]:
ascii=ord('a') #ASCII VALUE OF A
ascii

97

In [124]:
chr(ascii)

'a'

In [125]:
#Can you do like this range (97 to 122+1) cause z is 122 and loop end on 122 so add 1
ord('z')

122

In [126]:
l1=[i for i in range(97,123)]
l1

[97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122]

In [127]:
for i in l1:
    print(chr(i))

a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z


**NOW CREATE ARRAY OF ALPHABETS**

In [119]:
letters_array = np.array([chr(i) for i in range(ord('a'), ord('z') + 1)])

In [120]:
letters_array

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
       'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],
      dtype='<U1')

In [50]:
np.array([1,2,3])

array([1, 2, 3])

Array of String List

In [51]:
print(np.array(['A','B','C']));type(np.array(['A','B','C']))

['A' 'B' 'C']


numpy.ndarray

**Array of tuple**

In [52]:
np.array((1,2,3)) #dtype int64

array([1, 2, 3])

**Array of Dictionary**

In [53]:
np.array({'Name':'Nitin','Age':25,'City':'Mumbai'})

array({'Name': 'Nitin', 'Age': 25, 'City': 'Mumbai'}, dtype=object)

**2D Array of Numerics**

In [54]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

**3D Array of Numerics**

In [55]:
np.array([['A','B','C'],['D','E','F']])

array([['A', 'B', 'C'],
       ['D', 'E', 'F']], dtype='<U1')

**Sequence of Python as Array**

In [56]:
l=[1,2,3,4] #List as Array
np.array(l)

array([1, 2, 3, 4])

In [57]:
t=(1,2,3,4) #Tuple as Array
np.array(t)

array([1, 2, 3, 4])

In [58]:
d={'A':'a','B':'b'}
np.array(d)

array({'A': 'a', 'B': 'b'}, dtype=object)

**Defining Dtype inside Array**

In [59]:
l=[1,2,3,4] #That List Elements Becomes Float
np.array(l,dtype=float)

array([1., 2., 3., 4.])

In [60]:
l=[1,2,3,4] #Tht list Elements Ebcome Objects
np.array(l,dtype=object)

array([1, 2, 3, 4], dtype=object)

In [61]:
l=['MUMBAI','Pune',0,None] #That List Elements Becomes BOOL Values
np.array(l,dtype=bool)

array([ True,  True, False, False])

**range functions**

In [62]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.arange(1,20,2) #Steping of 2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [64]:
np.arange(1,11).reshape(2,5) # Reshaping Array Elements 2Rows 5 Columns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [65]:
np.array(['A','B','C','D']).reshape(2,2) #Also Work with 1D Array of String

array([['A', 'B'],
       ['C', 'D']], dtype='<U1')

In [66]:
import pandas as pd
g=np.array(['A','B','C','D']).reshape(2,2) #Remeber this Techniques: We can also Converts in into DataFrame
pd.DataFrame(g)

0  1
0  A  B
1  C  D

**Initializing 0s and 1s**

In [67]:
np.ones(2) #Makes array of one of 2 elements

array([1., 1.])

In [68]:
np.zeros(3) #Makes array of zeros of 3 elements

array([0., 0., 0.])

In [69]:
np.ones(10).reshape(2,5) #We also use reshape of this

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [70]:
np.zeros(12).reshape(2,6) # Remeber the 2, 6 is always multiple of size array meanss 12 will be 2,6 or 6,2 or 3, 4 or 4,3 or 1,12 or 12,1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

**linespace : Linearly Seperable Points**

In [71]:
np.linspace(1,2) #Will Make 50 pointv that are linearly distribute from gievn points

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [72]:
np.linspace(1,2,5) #Only I want 5 point linearly distributed

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

**Making Identity Matrix**

In [73]:
np.identity(3) #Makes Diagonal of one with all 0s Default is float output

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
np.identity(3,dtype=int) #We can specify dtype

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**Attibutes**

**ndim**

In [75]:
#ndim Tells dimension in single not writebale numeric value ,
l=np.array([1,2])
l.ndim

1

In [76]:
l=np.array([[1,2],[3,4]])
l.ndim

2

In [77]:
l=np.array([1,2,3,4,5,6,7,8,9]).reshape(1,3,3)
l.ndim

3

**dtype** <br>
show dtype (Data Type of Each whole array what type of elements there)

In [78]:
l=np.array([12,24,36])
l.dtype

dtype('int64')

In [79]:
l=np.array([1.2,2.4,3.6])
l.dtype

dtype('float64')

In [80]:
l=np.array(['1'])
l.dtype

dtype('<U1')

In [81]:
l=np.array([True])
l.dtype

dtype('bool')

In [82]:
l=np.array([1+3j])
l.dtype

dtype('complex128')

**shape**

In [83]:
l=np.array([1,2,3,4,5,6,7]) #How much Elements in 0s Level
l.shape

(7,)

In [84]:
l=np.array([[1,2],[3,4],[5,6]]) #Show Outer Level elements count, then Inside 2nd Levels element count
l.shape

(3, 2)

In [85]:
l=np.array([[[1],[2],[3]],[[3],[4],[5]]]) #Show Outer Level, count, then 2nd level then 0th level
l.shape

(2, 3, 1)

**itemsize** <br>
show size in byte for elements in memory

In [86]:
l=np.array([[[1],[2],[3]],[[3],[4],[5]]])
l.itemsize  #int32 4byte  Default is int64 8byte

8

In [87]:
f=np.array([1.2,3.2],dtype='int32') #If you convert float into int32 and check it is taking 4 byte
f.itemsize

4

In [88]:
#32 bit dtype occupied less memory as 64 bit dtype for both int and float

**Changing Data Type of Any Array (Limitation)**

In [89]:
a=np.array([1,2,3])
a.dtype

dtype('int64')

In [90]:
a.astype('int32') #I want in32, because int64 is occupying more memory

array([1, 2, 3], dtype=int32)

In [91]:
a #Now dtype Changed

array([1, 2, 3])

especially when dealing with large datasets where every bit of memory optimization can make a significant difference.

**Array Operations**

In [92]:
#Element Wise Addition (Vector Operations)
a=np.array([1,2,3,4,5])
x=np.array([1,2,3,4,5])
a+x

array([ 2,  4,  6,  8, 10])

In [93]:
a-x

array([0, 0, 0, 0, 0])

In [106]:
a/x

array([1., 1., 1., 1., 1.])

In [107]:
a*x

array([ 1,  4,  9, 16, 25])

In [108]:
a**x

array([   1,    4,   27,  256, 3125])

In [109]:
a//x

array([1, 1, 1, 1, 1])

**Scalar Operations**

In [94]:
a=np.array([1,2,3,4,5])
a+2 #Directly Add All Element by 2

array([3, 4, 5, 6, 7])

In [95]:
a-2

array([-1,  0,  1,  2,  3])

In [96]:
a*2

array([ 2,  4,  6,  8, 10])

In [97]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [110]:
a**2

array([ 1,  4,  9, 16, 25])

In [111]:
a//2

array([0, 1, 1, 2, 2])

**Relational Operation On Array**

In [98]:
a=np.array([1,2,3,4,5])
a>2

array([False, False,  True,  True,  True])

In [99]:
a<2

array([ True, False, False, False, False])

In [100]:
a==2

array([False,  True, False, False, False])

In [101]:
a!=2

array([ True, False,  True,  True,  True])

**Membership Operations**

In [102]:
a=np.array([1,2,3,4,5])
2 in a

True

**checks all numerics as List**

In [112]:

a=np.array([1,2,3,4,5]);[1,2,3,4,5] in a

True

In [113]:
(1,2,3) in a #Tuple form membership throw warning - Avoid this

<ipython-input-113-d178b75f76e4>:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  (1,2,3) in a


False

In [114]:
np.array([1,2,3,4,5]) is a

False

**Aggregation on Array**

*Aggregation on Array using Functions*

In [128]:
a=np.array([1,2,3,4,5]) #SUM
a.sum()

15

In [129]:
a.mean() #MEAN

3.0

In [130]:
a.max() #MAXIMUM

5

In [131]:
a.min() #MINIMUS

1

In [143]:
a.std() #Standard Deviation

1.4142135623730951

In [144]:
a.var() #VARIANCE

2.0

In [146]:
a.nonzero() #Check indices of non zeros, its showing indices of all non zeros

(array([0, 1, 2, 3, 4]),)

**Numpy Functions (np methods)**

In [147]:
np.abs(-1) #Absolute Value

1

In [148]:
y='Hello, World, How, Are, You'


In [158]:
y.split(', ') #split on this delimiter

['Hello', 'World', 'How', 'Are', 'You']

In [159]:
substrin=y.split(', ');substrin

['Hello', 'World', 'How', 'Are', 'You']

**If there is a string of list**

In [161]:
x=['A | B | C | D'] #If List so we have to convert them into str
str(x).split(' | ')

["['A", 'B', 'C', "D']"]

In [163]:
for i in x:
    print(str(i).split(' | '))

['A', 'B', 'C', 'D']


**If there is 2D String of List**

In [176]:
x=[['A | B | C | D'],
  ['E | F | G | H'],
  ['I | J | K | L'],
   ['M | N | O | P']]

In [177]:
str(x).split('|') #Thats not correct

["[['A ",
 ' B ',
 ' C ',
 " D'], ['E ",
 ' F ',
 ' G ',
 " H'], ['I ",
 ' J ',
 ' K ',
 " L'], ['M ",
 ' N ',
 ' O ',
 " P']]"]

In [178]:
for i in x[0]: #That Just Goes on 0th element
    print(i)

A | B | C | D


In [179]:
for i in range(0,len(x)):
    for j in x[i]:
        print(j)

A | B | C | D
E | F | G | H
I | J | K | L
M | N | O | P


In [180]:
list1=[]
for i in range(0,len(x)):
    for j in x[i]:
        list1.append(j.split(' | '))
print(list1)

[['A', 'B', 'C', 'D'], ['E', 'F', 'G', 'H'], ['I', 'J', 'K', 'L'], ['M', 'N', 'O', 'P']]


In [181]:
#Make this as array
np.array(list1)

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H'],
       ['I', 'J', 'K', 'L'],
       ['M', 'N', 'O', 'P']], dtype='<U1')

In [183]:
np.array(list1).reshape(4,4)

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H'],
       ['I', 'J', 'K', 'L'],
       ['M', 'N', 'O', 'P']], dtype='<U1')

In [184]:
data=np.array(list1).reshape(4,4)
import pandas as pd
df=pd.DataFrame(data)
df

0  1  2  3
0  A  B  C  D
1  E  F  G  H
2  I  J  K  L
3  M  N  O  P

**Substitution From Any Strings**

In [185]:
a='Naofil Momin 24 momin.naofil@gmail.com Bhiwandi'
a.split(' ')

['Naofil', 'Momin', '24', 'momin.naofil@gmail.com', 'Bhiwandi']

In [190]:
a.replace(' ','-',2) #Replace to 2 occurance of space

'Naofil-Momin-24 momin.naofil@gmail.com Bhiwandi'

In [193]:
a.split(' ',2) #maximum split become only 2

['Naofil', 'Momin', '24 momin.naofil@gmail.com Bhiwandi']

In [198]:
#Take Example
a='Momin Naofil 24 momin.naofil@gmail.com B.N.N. College of Arts science and Commerce'
a.split(' ',4)

['Momin',
 'Naofil',
 '24',
 'momin.naofil@gmail.com',
 'B.N.N. College of Arts science and Commerce']

**Findings in String**

In [201]:
a

'Momin Naofil 24 momin.naofil@gmail.com B.N.N. College of Arts science and Commerce'

In [202]:
a.find('i')

3

In [204]:
a.find('rce')

79

In [205]:
#But see if we give word so what happend its funny see
a.find('commerce')

-1

In [207]:
a.find(' and ')

69

In [209]:
len(a)

82

In [228]:
a='Momin Naofil 24 Mumbai BNN College Samad Nagar'
a.split(' ',4)

['Momin', 'Naofil', '24', 'Mumbai', 'BNN College Samad Nagar']

In [258]:
a = 'Momin Naofil 24 Mumbai BNN College Samad Nagar'
parts = a.split(' ', 4)
result = parts[:2] + [int(parts[2])] + [parts[3]]
result.append(parts[4])
print(result)


['Momin', 'Naofil', 24, 'Mumbai', 'BNN College Samad Nagar']


In [263]:
a.split(' ',4)
res=result[4][12:]
res

'Samad Nagar'

In [271]:
parts=a.split(' ',4)
parts[4]=parts[-1].split(' ',-1)[0]+" "+parts[-1].split(' ',-1)[1]+' \'' +res+'\''
parts

['Momin', 'Naofil', '24', 'Mumbai', "BNN College 'Samad Nagar'"]

**INDEXING in array**
<br> [] do you see this in previuos example<br>

In [274]:
a2=np.array([0,1,2,3,4,5,6,7,8,9,10,11]).reshape(3,4)

In [275]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [277]:
#Now retrive 2
a2[0][2] #Row 0 and inside that 2 index in 2

2